# Warehouse Parameters
n: 2               # n*m big racks where each rack has 25 small racks
m: 2
sorting_m: 10           # Sorting Window size
sorting_n: 6

# For Orders
type_of_items: 1        # Types of items in the Warehouse
max_diff_item: 2        # Max unique items that can be ordered
max_order_limit: 2      # Max quantity that can be ordered
order_freq: 1          # Order Frequency
truck_freq: 50       # Truck Frequency
initial_items: 500     # Initial Items assigned in racks

# For Agents
Number_of_Agents: 50    # Number of Rack Agents
Number_of_SAgents: 50   # Number of Sorting Agents
random_intersection_flag: 1  # 1 means Randomized Intersection Management, else Normal Intersection Management
epsilon: 0.75       # probability of randomisation in Intersection
congestion_flag: 0  # Congestion Flag 0 for no congestion, 1 for congestion management

# Single Bot All Items
SBIG: 1